#!/usr/bin/env python3
"""Generate the full GitHub Pages site: for every network in
fiducial_networks.FIDUCIAL_NETWORKS, generate the wasm-targeted solver
source (ChemicalNetwork.write_wasm_solver(), the Jinja-templated
src/dengo/templates/wasm_solver/dengo_wasm.cpp.template), compile it
with Emscripten, and write a page for it; plus one landing page linking
to all of them.

Requires `em++` on PATH (the Emscripten SDK -- see wasm/README.md; no
root needed to install). Run from anywhere:

    python3 wasm/generate_site.py [output_dir]

output_dir defaults to wasm/_site/ (gitignored -- this is a build
output, regenerated by CI on every push; see .github/workflows/
gh-pages.yml). Every network's build is independent and this script
continues past a single network's failure (reporting it at the end) --
one broken fiducial network shouldn't take down the whole site.
"""
import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from fiducial_networks import FIDUCIAL_NETWORKS  # noqa: E402
from reaction_rates import REACTION_RATES  # noqa: E402

EXPORTED_FUNCTIONS = [
    "_dengo_wasm_init", "_dengo_wasm_step", "_dengo_wasm_state_ptr",
    "_dengo_wasm_rhs_ptr", "_dengo_wasm_temperature", "_dengo_wasm_nspecies",
    "_dengo_wasm_species_names", "_malloc", "_free",
]

PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} -- dengo in the browser</title>
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>%F0%9F%A7%AA</text></svg>">
<link rel="stylesheet" href="../style.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css">
</head>
<body>
<div class="nav"><a href="../">&larr; all networks</a> <a href="rates.html">reaction rates &rarr;</a></div>
<h1 id="page-title">{title}</h1>
<p class="sub">
  Compiled to WebAssembly from dengo's generated solver (no Python, no server) --
  see <a href="https://github.com/{repo}/tree/main/wasm">wasm/</a> and
  <code>dengo.ChemicalNetwork.write_wasm_solver()</code>.
  Drag a slider and the chemistry re-solves and redraws immediately.
</p>

<div id="run-summary" class="run-summary">loading solver&hellip;</div>

<div class="layout">
  <div class="panel">
    <div class="row">
      <label>Initial conditions</label>
      <select id="ic-preset" disabled>
        <option value="">— custom —</option>
        <option value="bg-z20">IGM background (z ≈ 20)</option>
        <option value="bg-z1000">IGM background (z ≈ 1000)</option>
        <option value="virial-shock">Virial shock (10⁶ M☉ minihalo)</option>
        <option value="protostellar-disk">Primordial protostellar disk</option>
      </select>
      <p class="preset-note" id="preset-note"></p>
    </div>

    <div class="modebar">
      <button id="mode-cool" class="active">Cool at constant density</button>
      <button id="mode-freefall">Free-fall collapse</button>
    </div>

    <div class="row">
      <label>n<sub>H</sub> (cm<sup>-3</sup>) <span class="val" id="nH-val"></span></label>
      <input type="range" id="nH" min="-4" max="17" step="0.1" value="4">
    </div>
    <div class="row">
      <label>T (K) <span class="val" id="T-val"></span></label>
      <input type="range" id="T" min="1" max="4.7" step="0.05" value="3">
    </div>
    <details class="species-details" open>
      <summary>Initial species fractions</summary>
      <div id="species-sliders"></div>
    </details>
    <div class="row" id="dtf-row">
      <label>total time: 10<sup>x</sup> s <span class="val" id="dtf-val"></span></label>
      <input type="range" id="dtf" min="6" max="17" step="0.1" value="13">
    </div>
    <div class="row" id="ntarget-row" style="display:none">
      <label>target n: 10<sup>x</sup> cm<sup>-3</sup> <span class="val" id="ntarget-val"></span></label>
      <input type="range" id="ntarget" min="2" max="20" step="0.1" value="15">
      <p class="preset-note">Beyond ~10¹⁶ cm⁻³ this single-zone free-fall
        model (no hydrostatic core support, no shock/radiative-transfer
        physics) is no longer a realistic dynamical model of an actual
        protostar -- the range goes further anyway so you can watch the
        chemistry network's own H2 collisional-dissociation reactions
        (H2 + H &rarr; 3H, H2 + H2 &rarr; 2H + H2) play out.</p>

      <label>shock density: 10<sup>x</sup> cm<sup>-3</sup> <span class="val" id="nshock-val"></span></label>
      <input type="range" id="nshock" min="10" max="20" step="0.1" value="14">
      <label>shock Mach number <span class="val" id="mach-val"></span></label>
      <input type="range" id="mach" min="1" max="100" step="0.5" value="5">
      <p class="preset-note">Optional accretion-shock heating event, applied
        once, the first time density crosses the shock density above --
        a Rankine-Hugoniot jump (using the gas's own composition-weighted
        &gamma; at that moment and the Mach number here) applied to both
        density and thermal energy in a single step, on top of ordinary
        free-fall compression. Set Mach to 1 to disable it (a Mach-1
        "shock" is the zero-strength limit -- no jump at all). This
        doesn't model a real accretion shock's radius/mass-dependent
        infall speed -- Mach number is a free dial here, not derived --
        so treat it as "how strong a shock would it take", not a
        prediction of where or how strong a real one occurs.</p>
    </div>

    <div class="status-row">
      <div id="status">loading solver&hellip;</div>
      <button type="button" id="download-csv" disabled title="every step of the run currently on screen (not a sweep's several overlaid runs)">Download CSV</button>
    </div>
  </div>

  <div id="charts">
    <div class="chart-box">
      <div class="mini-modebar">
        <button type="button" id="T-mode-T" class="active">temperature</button>
        <button type="button" id="T-mode-ge">thermal energy</button>
      </div>
      <p class="preset-note" id="zoom-timespan"></p>
      <div id="chart-run"></div>
      <p class="preset-note">One combined view of the current run (a
        single Vega-Lite spec), stacked vertically: in free-fall mode,
        density vs. time-to-end, then temperature vs. density, a zoomed
        copy of that, then ionization/H₂ fraction, then species mass
        fraction -- cool mode drops the density-vs-time panel (density
        is held constant there, so it'd just be a flat line). Drag a
        rectangle on the temperature-vs-density (or, in cool mode,
        temperature-vs-time) panel to zoom every other panel -- including
        its own zoomed copy directly below it -- to the same range at
        once; that one panel itself stays at the full range, showing the
        selection box -- click it (without dragging) to clear the zoom.
        The selected range's real elapsed time is read out just above.
        The shaded band on the temperature panels marks 1500-2500 K, the
        H2-formation-heating-driven fragmentation regime this project
        targets -- orientation only, not a solver threshold. Click a
        legend entry (ionization/H₂, species) to isolate just that
        series, shift-click to isolate several at once, or click either
        one more time to show all again.</p>
    </div>
  </div>
</div>

<details class="sweep-section">
  <summary>Parameter sweep -- compare several starting conditions at once</summary>
  <p class="preset-note">Holds every other slider at its current setting,
    runs the current mode (cool/free-fall) once per value in the range
    below, and overlays all of them -- e.g. several starting
    temperatures, to see whether/when the gas "forgets" where it
    started. Not live -- a sweep is several full runs, not one, so it
    only runs when asked. Picking a parameter disables its regular
    slider (it's driven by the range below for the sweep instead) and
    re-enables it once you switch to sweeping something else.</p>
  <div class="row sweep-controls">
    <label>sweep over</label>
    <select id="sweep-param"></select>
    <label>from</label>
    <input type="number" id="sweep-start" step="any">
    <label>to</label>
    <input type="number" id="sweep-stop" step="any">
    <label>count</label>
    <input type="number" id="sweep-count" min="2" max="12" step="1" value="6">
    <button type="button" id="run-sweep" disabled>Run sweep</button>
    <span id="sweep-status" class="preset-note"></span>
  </div>
  <div id="sweep-charts">
    <div class="chart-box">
      <div class="chart-title">Temperature (sweep)</div>
      <div class="chart-row">
        <div class="axis-y" id="ylabel-sweep-T"></div>
        <div id="chart-sweep-T"></div>
      </div>
      <div class="axis-x" id="xlabel-sweep-T"></div>
    </div>
    <div class="chart-box">
      <div class="chart-title">H<sub>2</sub> fraction (sweep)</div>
      <div class="chart-row">
        <div class="axis-y" id="ylabel-sweep-h2"></div>
        <div id="chart-sweep-h2"></div>
      </div>
      <div class="axis-x" id="xlabel-sweep-h2"></div>
    </div>
  </div>
</details>

<script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@5"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
<script src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"></script>
<script src="dengo_wasm.js"></script>
<script src="../app.js"></script>
<script>
initPage({config_json});
</script>
</body>
</html>
"""

RATES_PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} reaction rates -- dengo in the browser</title>
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>%F0%9F%A7%AA</text></svg>">
<link rel="stylesheet" href="../style.css">
</head>
<body>
<div class="nav"><a href="../">&larr; all networks</a> <a href="index.html">&larr; {title} widget</a></div>
<h1>{title}: reaction rates</h1>
<p class="sub">
  Every reaction rate coefficient this network uses, plotted over its
  configured temperature range and editable in place (Vega expression
  syntax -- the same T/tev/logtev/logT variables
  <a href="https://github.com/{repo}/blob/main/src/dengo/primordial_rates.py">primordial_rates.py</a>'s
  own functions use). Changes here are exploratory only -- editing a
  formula updates its own plot immediately but does not (yet) feed back
  into the compiled solver on the <a href="index.html">widget page</a>.
  Select which reactions to show, then export the current set (including
  any edits) to a small JSON file, or load one back in.
</p>
<div class="rates-toolbar">
  <button type="button" id="rates-all">all</button>
  <button type="button" id="rates-none">none</button>
  <button type="button" id="rates-reset">reset edits</button>
  <span class="rates-toolbar-spacer"></span>
  <button type="button" id="rates-export">Download JSON</button>
  <label class="rates-upload-label">Upload JSON
    <input type="file" id="rates-import" accept="application/json">
  </label>
</div>
<div id="rate-toggle" class="species-toggle"></div>
<div id="rate-cards"></div>

<script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@5"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
<script src="../rates.js"></script>
<script>
initRatesPage({config_json});
</script>
</body>
</html>
"""

LANDING_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Dengo in the browser</title>
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>%F0%9F%A7%AA</text></svg>">
<link rel="stylesheet" href="style.css">
</head>
<body>
<h1>Dengo in the browser</h1>
<p class="sub">
  Interactive chemistry/cooling solvers, compiled to WebAssembly straight from
  dengo's generated C++ -- no Python, no server, no Jupyter kernel. Pick a
  network below; each is its own independently-generated/-compiled solver
  (<code>ChemicalNetwork.write_wasm_solver()</code>).
</p>
<ul class="network-list">
{items}
</ul>
</body>
</html>
"""


def find_emxx():
    emxx = shutil.which("em++")
    if emxx is None:
        print("em++ not found on PATH -- install/activate the Emscripten SDK "
              "(https://emscripten.org/docs/getting_started/downloads.html)", file=sys.stderr)
        sys.exit(1)
    return emxx


def build_rates_page(network, cfg, net_dir, repo):
    """The reaction-rate viewer needs none of the compiled solver -- just
    the network's own reaction list (to filter REACTION_RATES down to
    what this particular network actually uses) and its configured
    temperature range (network.T, set by init_temperature() during
    cfg["build"]()). No em++ involved at all."""
    reaction_names = sorted(network.reactions.keys())
    rates = {name: REACTION_RATES[name] for name in reaction_names if name in REACTION_RATES}
    missing = [name for name in reaction_names if name not in REACTION_RATES]
    if missing:
        print("!!! reaction_rates.py has no transcription for: %s (omitted from rates page)"
              % missing, file=sys.stderr)
    config = {
        "title": cfg["title"],
        "Tmin": float(network.T.min()),
        "Tmax": float(network.T.max()),
        "rates": rates,
    }
    with open(os.path.join(net_dir, "rates.html"), "w") as f:
        f.write(RATES_PAGE_TEMPLATE.format(
            title=cfg["title"], repo=repo, config_json=json.dumps(config),
        ))


def build_one(name, cfg, out_dir, repo):
    net_dir = os.path.join(out_dir, name)
    os.makedirs(net_dir, exist_ok=True)

    network = cfg["build"]()
    build_rates_page(network, cfg, net_dir, repo)
    network.write_wasm_solver(name, output_dir=net_dir)

    subprocess.run(
        [
            find_emxx(), "-O3", "-o", "dengo_wasm.js",
            "dengo_wasm.cpp", "%s_solver.C" % name, "BE_chem_solve.C",
            "--embed-file", "%s_tables.bin@%s_tables.bin" % (name, name),
            "-sEXPORTED_FUNCTIONS=%s" % ",".join(EXPORTED_FUNCTIONS),
            "-sEXPORTED_RUNTIME_METHODS=cwrap,ccall,HEAPF64",
            "-sMODULARIZE=1", "-sEXPORT_NAME=DengoModule",
            "-sALLOW_MEMORY_GROWTH=1",
        ],
        cwd=net_dir, check=True,
    )

    species_names = sorted(s.name for s in network.required_species)
    config = {
        "title": cfg["title"],
        "default_ics": cfg["default_ics"],
        "default_T": cfg["default_T"],
        "species_names": species_names,
    }
    with open(os.path.join(net_dir, "index.html"), "w") as f:
        f.write(PAGE_TEMPLATE.format(
            title=cfg["title"], repo=repo, config_json=json.dumps(config),
        ))

    # generated build byproducts not needed by the served page
    for fn in ("%s_solver.h" % name, "%s_solver.C" % name, "BE_chem_solve.C",
               "%s_tables.bin" % name, "dengo_wasm.cpp"):
        os.remove(os.path.join(net_dir, fn))


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "_site")
    repo = os.environ.get("GITHUB_REPOSITORY", "data-exp-lab/dengo")
    # Fail fast, before creating/touching out_dir at all. find_emxx() calls
    # sys.exit(1) if em++ isn't on PATH -- SystemExit isn't an Exception,
    # so it isn't caught by the per-network try/except below; left
    # unchecked here, that meant the whole process died partway through
    # the *first* network (right after codegen, before compiling it),
    # leaving a half-built out_dir/ with generated .C files but no
    # compiled .js/.wasm and no index.html anywhere, including no landing
    # page -- confusing (looks like a bare directory listing when served)
    # rather than the clear "install/activate the Emscripten SDK" message
    # that was actually printed.
    find_emxx()
    os.makedirs(out_dir, exist_ok=True)

    shutil.copy(os.path.join(HERE, "app.js"), out_dir)
    shutil.copy(os.path.join(HERE, "rates.js"), out_dir)
    shutil.copy(os.path.join(HERE, "style.css"), out_dir)
    # dengo-solver.js/.d.ts: a reusable wrapper around any dengo-generated
    # wasm module, not specific to any one network -- copied once at the
    # top level, same as the above, not duplicated per network.
    shutil.copy(os.path.join(HERE, "dengo-solver.js"), out_dir)
    shutil.copy(os.path.join(HERE, "dengo-solver.d.ts"), out_dir)

    succeeded, failed = [], []
    for name, cfg in FIDUCIAL_NETWORKS.items():
        print("--- building %s ---" % name)
        try:
            build_one(name, cfg, out_dir, repo)
            succeeded.append(name)
        except Exception as exc:
            print("!!! %s failed: %s" % (name, exc), file=sys.stderr)
            failed.append(name)

    items = "\n".join(
        '  <li><a href="%s/">%s</a><div class="desc">%s</div></li>'
        % (name, FIDUCIAL_NETWORKS[name]["title"], FIDUCIAL_NETWORKS[name]["build"].__doc__.strip().split("\n")[0])
        for name in succeeded
    )
    with open(os.path.join(out_dir, "index.html"), "w") as f:
        f.write(LANDING_TEMPLATE.format(items=items))

    print("\nsucceeded: %s" % succeeded)
    if failed:
        print("FAILED: %s" % failed, file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
